export const LANGUAGES = [
  "Русский", "Английский", "Немецкий", "Французский", "Испанский",
  "Китайский (мандаринский)", "Японский", "Итальянский", "Португальский",
  "Арабский", "Корейский", "Турецкий", "Польский", "Нидерландский",
  "Шведский", "Норвежский", "Датский", "Финский", "Чешский", "Венгерский",
  "Украинский", "Белорусский", "Казахский", "Грузинский", "Армянский",
];

// Города по странам для фильтрации
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Россия": [
    "Москва", "Санкт-Петербург", "Новосибирск", "Екатеринбург", "Казань",
    "Нижний Новгород", "Челябинск", "Самара", "Уфа", "Ростов-на-Дону",
    "Красноярск", "Воронеж", "Пермь", "Волгоград", "Краснодар",
    "Тюмень", "Саратов", "Тольятти", "Ижевск", "Барнаул",
    "Ульяновск", "Иркутск", "Хабаровск", "Ярославль", "Владивосток",
    "Махачкала", "Томск", "Оренбург", "Кемерово", "Новокузнецк",
    "Рязань", "Астрахань", "Пенза", "Набережные Челны", "Липецк",
    "Тула", "Киров", "Чебоксары", "Калининград", "Брянск",
    "Курск", "Магнитогорск", "Иваново", "Тверь", "Ставрополь",
    "Белгород", "Архангельск", "Владимир", "Сочи", "Сургут",
  ],
  "США": [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "San Francisco",
    "Charlotte", "Indianapolis", "Seattle", "Denver", "Nashville",
    "Boston", "Las Vegas", "Portland", "Memphis", "Atlanta",
    "Miami", "Minneapolis", "New Orleans", "Washington D.C.", "Detroit",
  ],
  "United States": [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "San Francisco", "Seattle", "Boston", "Miami", "Atlanta",
    "Dallas", "Denver", "Austin", "Las Vegas", "Washington D.C.",
  ],
  "Германия": [
    "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt",
    "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen",
    "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg",
  ],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart"],
  "Великобритания": [
    "London", "Birmingham", "Manchester", "Glasgow", "Leeds",
    "Liverpool", "Bristol", "Edinburgh", "Sheffield", "Leicester",
    "Cardiff", "Coventry", "Nottingham", "Bradford", "Belfast",
  ],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Glasgow", "Edinburgh", "Bristol"],
  "Франция": ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Bordeaux", "Strasbourg"],
  "France": ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Bordeaux"],
  "Испания": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Bilbao"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville"],
  "Италия": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Venice"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Florence", "Venice"],
  "Польша": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Katowice"],
  "Нидерланды": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "Швеция": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linköping"],
  "Норвегия": ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  "Дания": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  "Финляндия": ["Helsinki", "Tampere", "Turku", "Oulu"],
  "Швейцария": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  "Австрия": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  "Бельгия": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
  "Португалия": ["Lisbon", "Porto", "Braga", "Coimbra"],
  "Чехия": ["Prague", "Brno", "Ostrava", "Plzeň"],
  "Венгрия": ["Budapest", "Debrecen", "Miskolc", "Pécs"],
  "Румыния": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
  "Греция": ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  "Израиль": ["Tel Aviv", "Jerusalem", "Haifa", "Beer Sheva", "Netanya"],
  "Israel": ["Tel Aviv", "Jerusalem", "Haifa"],
  "Турция": ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep"],
  "Turkey": ["Istanbul", "Ankara", "Izmir"],
  "ОАЭ": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  "UAE": ["Dubai", "Abu Dhabi", "Sharjah"],
  "Китай": ["Shanghai", "Beijing", "Shenzhen", "Guangzhou", "Chengdu", "Wuhan", "Xi'an", "Hangzhou"],
  "China": ["Shanghai", "Beijing", "Shenzhen", "Guangzhou"],
  "Япония": ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Kobe", "Kyoto", "Fukuoka"],
  "Japan": ["Tokyo", "Osaka", "Yokohama", "Nagoya"],
  "Южная Корея": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  "South Korea": ["Seoul", "Busan", "Incheon"],
  "Индия": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  "Сингапур": ["Singapore"],
  "Singapore": ["Singapore"],
  "Канада": ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa", "Edmonton", "Winnipeg", "Quebec City"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa"],
  "Австралия": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "Новая Зеландия": ["Auckland", "Wellington", "Christchurch"],
  "Бразилия": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte"],
  "Аргентина": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
  "Мексика": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  "Казахстан": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe"],
  "Беларусь": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  "Украина": ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Lviv"],
  "Грузия": ["Tbilisi", "Batumi", "Kutaisi"],
  "Армения": ["Yerevan", "Gyumri", "Vanadzor"],
  "Азербайджан": ["Baku", "Ganja", "Sumqayit"],
  "Узбекистан": ["Tashkent", "Samarkand", "Namangan", "Andijan"],
  "Кыргызстан": ["Bishkek", "Osh"],
};

// Получить города для страны (с fallback на все города)
export function getCitiesForCountry(country: string): string[] {
  if (!country) return ALL_CITIES;
  const key = Object.keys(CITIES_BY_COUNTRY).find(
    (k) => k.toLowerCase() === country.toLowerCase()
  );
  return key ? CITIES_BY_COUNTRY[key] : ALL_CITIES;
}

const ALL_CITIES = Object.values(CITIES_BY_COUNTRY).flat();

export const CITIES = [
  // Россия
  "Москва", "Санкт-Петербург", "Новосибирск", "Екатеринбург", "Казань",
  "Нижний Новгород", "Челябинск", "Самара", "Уфа", "Ростов-на-Дону",
  "Красноярск", "Воронеж", "Пермь", "Волгоград", "Краснодар",
  "Тюмень", "Саратов", "Тольятти", "Ижевск", "Барнаул",
  "Ульяновск", "Иркутск", "Хабаровск", "Ярославль", "Владивосток",
  "Махачкала", "Томск", "Оренбург", "Кемерово", "Новокузнецк",
  "Рязань", "Астрахань", "Пенза", "Набережные Челны", "Липецк",
  "Тула", "Киров", "Чебоксары", "Калининград", "Брянск",
  "Курск", "Магнитогорск", "Иваново", "Тверь", "Ставрополь",
  "Белгород", "Архангельск", "Владимир", "Сочи", "Сургут",
  // США
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
  "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
  "Austin", "Jacksonville", "Fort Worth", "Columbus", "San Francisco",
  "Charlotte", "Indianapolis", "Seattle", "Denver", "Nashville",
  "Boston", "Las Vegas", "Portland", "Memphis", "Atlanta",
  "Miami", "Minneapolis", "New Orleans", "Washington D.C.", "Detroit",
  // Европа
  "London", "Paris", "Berlin", "Madrid", "Rome",
  "Amsterdam", "Vienna", "Warsaw", "Prague", "Lisbon",
  "Stockholm", "Oslo", "Copenhagen", "Helsinki", "Dublin",
  "Brussels", "Zurich", "Geneva", "Barcelona", "Munich",
  "Hamburg", "Milan", "Naples", "Turin", "Frankfurt",
  "Lyon", "Marseille", "Toulouse", "Rotterdam", "Antwerp",
  "Budapest", "Bucharest", "Sofia", "Athens", "Belgrade",
  "Zagreb", "Ljubljana", "Bratislava", "Tallinn", "Riga", "Vilnius",
  // Азия
  "Tokyo", "Shanghai", "Beijing", "Seoul", "Mumbai",
  "Delhi", "Bangalore", "Singapore", "Hong Kong", "Bangkok",
  "Jakarta", "Kuala Lumpur", "Manila", "Taipei", "Ho Chi Minh City",
  "Osaka", "Shenzhen", "Guangzhou", "Chengdu", "Wuhan",
  "Dubai", "Abu Dhabi", "Riyadh", "Istanbul", "Tehran",
  "Baghdad", "Karachi", "Lahore", "Dhaka", "Colombo",
  "Kathmandu", "Almaty", "Tashkent", "Baku", "Tbilisi",
  "Yerevan", "Astana", "Bishkek", "Dushanbe", "Ashgabat",
  // Другие регионы
  "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland",
  "Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa",
  "Mexico City", "São Paulo", "Rio de Janeiro", "Buenos Aires", "Bogotá",
  "Lima", "Santiago", "Caracas", "Quito", "La Paz",
  "Cairo", "Lagos", "Nairobi", "Johannesburg", "Cape Town",
  "Casablanca", "Accra", "Addis Ababa", "Dar es Salaam", "Kinshasa",
];

export const UNIVERSITIES = [
  // Россия
  "МГУ им. Ломоносова", "СПбГУ", "МГТУ им. Баумана",
  "НГУ (Новосибирский государственный университет)", "МФТИ (Физтех)",
  "НИУ ВШЭ (Высшая школа экономики)", "Университет ИТМО",
  "МГИМО", "РАНХиГС", "Финансовый университет при Правительстве РФ",
  "РЭУ им. Плеханова", "УрФУ", "КФУ", "ТГУ", "СФУ", "ДВФУ", "ЮФУ",
  "РУДН", "МАИ", "НИТУ МИСИС", "СПбПУ им. Петра Великого",
  "ЛЭТИ (СПбГЭТУ)", "МИЭТ", "Сколтех", "РГУ нефти и газа им. Губкина",
  // США
  "MIT (Massachusetts Institute of Technology)", "Stanford University",
  "Harvard University", "Caltech", "UC Berkeley",
  "Princeton University", "Yale University", "Columbia University",
  "University of Pennsylvania", "Cornell University",
  "University of Michigan", "UCLA", "University of Chicago",
  "Carnegie Mellon University", "Johns Hopkins University",
  "Duke University", "Northwestern University", "NYU",
  "University of Washington", "Georgia Tech",
  // Великобритания
  "University of Oxford", "University of Cambridge", "Imperial College London",
  "UCL (University College London)", "London School of Economics (LSE)",
  "University of Edinburgh", "King's College London",
  "University of Manchester", "University of Bristol",
  // Европа
  "ETH Zurich", "EPFL", "TU Munich", "LMU Munich",
  "University of Amsterdam", "Delft University of Technology",
  "KU Leuven", "Ghent University", "University of Copenhagen",
  "Uppsala University", "Lund University", "University of Helsinki",
  "Sorbonne University", "Sciences Po", "Polytechnique",
  "INSEAD", "HEC Paris", "TU Berlin", "Heidelberg University",
  "University of Vienna", "University of Warsaw", "Charles University Prague",
  // Азия
  "University of Tokyo", "Peking University", "Tsinghua University",
  "Seoul National University", "KAIST", "NUS (National University of Singapore)",
  "Nanyang Technological University", "University of Hong Kong",
  "HKUST", "Chinese University of Hong Kong",
  "IIT Bombay", "IIT Delhi", "Indian Institute of Science",
  // Другие
  "University of Toronto", "University of British Columbia", "McGill University",
  "University of Melbourne", "Australian National University", "University of Sydney",
  "University of São Paulo", "Universidad Nacional Autónoma de México",
];

export const SPECIALIZATIONS = [
  "Информатика и вычислительная техника",
  "Программная инженерия",
  "Прикладная математика и информатика",
  "Информационные системы и технологии",
  "Кибербезопасность",
  "Искусственный интеллект",
  "Анализ данных и машинное обучение",
  "Бизнес-информатика",
  "Компьютерные науки",
  "Математика",
  "Физика",
  "Электроника и наноэлектроника",
  "Телекоммуникации",
  "Менеджмент",
  "Экономика",
  "Финансы и кредит",
  "Маркетинг",
  "Логистика",
  "Управление персоналом",
  "Юриспруденция",
  "Лингвистика",
  "Психология",
  "Педагогика",
  "Биология",
  "Химия",
  "Медицина",
  "Дизайн",
  "Архитектура",
  "Журналистика",
  "Социология",
];

export const PROFESSIONS = [
  // IT & разработка
  "Frontend Developer", "Frontend-разработчик",
  "Backend Developer", "Backend-разработчик",
  "Fullstack Developer", "Fullstack-разработчик",
  "Mobile Developer (iOS)", "Mobile Developer (Android)",
  "iOS-разработчик", "Android-разработчик",
  "DevOps Engineer", "DevOps-инженер",
  "Site Reliability Engineer (SRE)",
  "Cloud Engineer", "Облачный инженер",
  "Software Engineer", "Инженер-программист",
  // Data & AI
  "Data Scientist", "Дата-сайентист",
  "Data Analyst", "Аналитик данных",
  "Data Engineer", "Инженер данных",
  "ML Engineer", "ML-инженер",
  "AI Engineer", "AI-инженер",
  "MLOps Engineer",
  "NLP Engineer", "Computer Vision Engineer",
  "Business Intelligence Analyst", "BI-аналитик",
  // Безопасность
  "Cybersecurity Engineer", "Инженер по кибербезопасности",
  "Security Analyst", "Аналитик безопасности",
  "Penetration Tester", "Пентестер",
  // Дизайн
  "UX/UI Designer", "UX/UI-дизайнер",
  "Product Designer", "Продуктовый дизайнер",
  "Graphic Designer", "Графический дизайнер",
  "Motion Designer", "Моушн-дизайнер",
  "Web Designer", "Веб-дизайнер",
  // Менеджмент & продукт
  "Product Manager", "Продакт-менеджер",
  "Project Manager", "Проджект-менеджер",
  "Scrum Master", "Agile Coach",
  "Technical Lead", "Технический лид",
  "Engineering Manager",
  // Аналитика & бизнес
  "Business Analyst", "Бизнес-аналитик",
  "System Analyst", "Системный аналитик",
  "Financial Analyst", "Финансовый аналитик",
  "Marketing Analyst", "Маркетинговый аналитик",
  // QA
  "QA Engineer", "QA-инженер",
  "Test Automation Engineer", "SDET",
  "Manual QA", "Ручной тестировщик",
  // Другие IT
  "Technical Writer", "Технический писатель",
  "IT Recruiter", "IT-рекрутер",
  "Game Developer", "Разработчик игр",
  "Blockchain Developer", "Blockchain-разработчик",
  "AR/VR Developer",
];

export const COUNTRIES = [
  "Россия", "США", "Германия", "Великобритания", "Франция",
  "Италия", "Испания", "Польша", "Нидерланды", "Швеция",
  "Норвегия", "Дания", "Финляндия", "Швейцария", "Австрия",
  "Бельгия", "Португалия", "Чехия", "Венгрия", "Румыния",
  "Греция", "Ирландия", "Израиль", "Турция", "ОАЭ",
  "Китай", "Япония", "Южная Корея", "Индия", "Сингапур",
  "Канада", "Австралия", "Новая Зеландия", "Бразилия", "Аргентина",
  "Мексика", "Казахстан", "Беларусь", "Украина", "Грузия",
  "Армения", "Азербайджан", "Узбекистан", "Кыргызстан",
  "United States", "Germany", "United Kingdom", "France", "Netherlands",
  "Canada", "Australia", "Switzerland", "Sweden", "Japan",
];
